"use client"

/**
 * app/invite/page.tsx
 *
 * Opened via /invite?token=...  (link generated by admin via POST /auth/invite)
 * Decodes the JWT client-side to prefill name + email (payload is not secret).
 * On submit → POST /auth/register → account created → success screen → /login
 */

import { useState, useEffect, type FormEvent } from "react"
import Image from "next/image"
import { useRouter, useSearchParams } from "next/navigation"
import { Check } from "lucide-react"

const API_BASE = process.env.NEXT_PUBLIC_API_BASE || "http://127.0.0.1:8000"

type InvitePreview = { email: string; full_name: string }

export default function InvitePage() {
  const router = useRouter()
  const searchParams = useSearchParams()
  const token = searchParams.get("token")

  const [preview, setPreview]       = useState<InvitePreview | null>(null)
  const [tokenError, setTokenError] = useState<string | null>(null)
  const [password, setPassword]     = useState("")
  const [confirm, setConfirm]       = useState("")
  const [formError, setFormError]   = useState<string | null>(null)
  const [loading, setLoading]       = useState(false)
  const [registered, setRegistered] = useState(false)

  // Decode JWT payload client-side for display only (not for trust)
  useEffect(() => {
    if (!token) {
      setTokenError("No invite token found. Please use the full link from your invitation email.")
      return
    }
    try {
      const [, b64] = token.split(".")
      const payload = JSON.parse(atob(b64.replace(/-/g, "+").replace(/_/g, "/")))
      if (payload.type !== "invite") throw new Error()
      if (Date.now() > payload.exp * 1000) {
        setTokenError("This invite link has expired (48 h limit). Ask your admin for a new one.")
        return
      }
      setPreview({ email: payload.email, full_name: payload.full_name })
    } catch {
      setTokenError("This invite link is invalid. Please ask your admin for a new one.")
    }
  }, [token])

  async function handleSubmit(e: FormEvent) {
    e.preventDefault()
    setFormError(null)
    if (password.length < 8) { setFormError("Password must be at least 8 characters."); return }
    if (password !== confirm) { setFormError("Passwords don't match."); return }

    setLoading(true)
    try {
      const res = await fetch(`${API_BASE}/auth/register`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        credentials: "include",
        body: JSON.stringify({ invite_token: token, password }),
      })
      if (!res.ok) {
        const err = await res.json().catch(() => ({ detail: "Registration failed" }))
        throw new Error(err.detail ?? "Registration failed")
      }
      setRegistered(true)
    } catch (err: unknown) {
      setFormError(err instanceof Error ? err.message : "Something went wrong")
    } finally {
      setLoading(false)
    }
  }

  return (
    <>
      <style>{css}</style>
      <div className="inv-root">
        <div className="inv-card">

          {/* Logo */}
          <div className="inv-logo">
            <Image src="/GoteeOff_logo.png" alt="GoTeeOff" width={34} height={34} className="rounded-lg" style={{ objectFit: "contain" }} />
            <div className="inv-logo-text">
              <span className="inv-logo-name">GoTeeOff</span>
              <span className="inv-logo-sub">CRM</span>
            </div>
          </div>

          {/* Success state */}
          {registered && (
            <div className="inv-success">
              <div className="inv-success-icon">
                <Check className="size-6" strokeWidth={2.5} />
              </div>
              <h2>Account created!</h2>
              <p>Your account is ready. Sign in with your new password to continue.</p>
              <button className="inv-btn" onClick={() => router.push("/login")}>
                Go to login
              </button>
            </div>
          )}

          {/* Token error state */}
          {!registered && tokenError && (
            <div className="inv-token-error">
              <div className="inv-err-icon">
                <svg width="22" height="22" viewBox="0 0 22 22" fill="none">
                  <circle cx="11" cy="11" r="9.5" stroke="#f87171" strokeWidth="1.5"/>
                  <path d="M11 7v4.5M11 14.5h.01" stroke="#f87171" strokeWidth="1.5" strokeLinecap="round"/>
                </svg>
              </div>
              <h2>Invalid invite</h2>
              <p>{tokenError}</p>
            </div>
          )}

          {/* Loading preview */}
          {!registered && !tokenError && !preview && (
            <div className="inv-loading">
              <span className="inv-spinner" />
              <p>Validating your invite…</p>
            </div>
          )}

          {/* Form */}
          {!registered && !tokenError && preview && (
            <>
              <div className="inv-head">
                <h1>You're invited</h1>
                <p>
                  Set a password to activate your GoTeeOff account for{" "}
                  <strong>{preview.email}</strong>.
                </p>
              </div>

              <div className="inv-meta">
                <div className="inv-meta-row">
                  <span className="inv-meta-label">Name</span>
                  <span className="inv-meta-value">{preview.full_name}</span>
                </div>
                <div className="inv-meta-row">
                  <span className="inv-meta-label">Email</span>
                  <span className="inv-meta-value">{preview.email}</span>
                </div>
              </div>

              <form onSubmit={handleSubmit} className="inv-form" noValidate>
                <div className="inv-field">
                  <label htmlFor="inv-pw">Password</label>
                  <input
                    id="inv-pw" type="password" autoComplete="new-password"
                    placeholder="At least 8 characters"
                    value={password} onChange={(e) => setPassword(e.target.value)}
                    required disabled={loading}
                  />
                </div>

                <div className="inv-field">
                  <label htmlFor="inv-pw2">Confirm password</label>
                  <input
                    id="inv-pw2" type="password" autoComplete="new-password"
                    placeholder="Repeat your password"
                    value={confirm} onChange={(e) => setConfirm(e.target.value)}
                    required disabled={loading}
                  />
                </div>

                {/* Password strength bar */}
                {password.length > 0 && (
                  <div className="inv-strength">
                    <div className="inv-strength-bar">
                      <div
                        className="inv-strength-fill"
                        style={{
                          width: `${Math.min(100, (password.length / 16) * 100)}%`,
                          background: password.length < 8 ? "#f87171"
                            : password.length < 12 ? "#fbbf24" : "#00e5a0",
                        }}
                      />
                    </div>
                    <span className="inv-strength-label">
                      {password.length < 8 ? "Too short" : password.length < 12 ? "Good" : "Strong"}
                    </span>
                  </div>
                )}

                {formError && (
                  <div className="inv-error" role="alert">
                    <svg width="15" height="15" viewBox="0 0 15 15" fill="none">
                      <circle cx="7.5" cy="7.5" r="6.5" stroke="#f87171" strokeWidth="1.5"/>
                      <path d="M7.5 4.5v3M7.5 10h.01" stroke="#f87171" strokeWidth="1.5" strokeLinecap="round"/>
                    </svg>
                    {formError}
                  </div>
                )}

                <button type="submit" className="inv-btn" disabled={loading}>
                  {loading ? <span className="inv-spinner-sm" /> : "Activate account"}
                </button>
              </form>
            </>
          )}
        </div>
      </div>
    </>
  )
}

const css = `
  .inv-root {
    min-height: 100vh; display: flex; align-items: center; justify-content: center;
    background: #09090f; padding: 32px 20px;
    font-family: var(--font-sans, Inter, sans-serif);
  }

  .inv-card {
    width: 100%; max-width: 420px;
    background: #111118; border: 1px solid #252530; border-radius: 16px;
    padding: 40px 36px; display: flex; flex-direction: column; gap: 28px;
  }

  /* logo */
  .inv-logo { display: flex; align-items: center; gap: 11px; }
  .inv-logo-mark {
    display: flex; align-items: center; justify-content: center;
    width: 34px; height: 34px; border-radius: 8px;
    background: rgba(0,229,160,0.12); color: #00e5a0;
    font-size: 12px; font-weight: 700; letter-spacing: 0.03em;
  }
  .inv-logo-text  { display: flex; flex-direction: column; gap: 1px; }
  .inv-logo-name  { font-size: 15px; font-weight: 700; color: #00e5a0; }
  .inv-logo-sub   { font-size: 10px; text-transform: uppercase; letter-spacing: 0.08em; color: #55556a; }

  /* token error */
  .inv-token-error {
    display: flex; flex-direction: column; align-items: center;
    text-align: center; gap: 12px; padding: 12px 0;
  }
  .inv-err-icon {
    width: 50px; height: 50px; border-radius: 50%;
    background: rgba(248,113,113,0.08); border: 1px solid rgba(248,113,113,0.2);
    display: flex; align-items: center; justify-content: center;
  }
  .inv-token-error h2 { font-size: 17px; font-weight: 600; color: #e8e8f0; }
  .inv-token-error p  { font-size: 14px; color: #9494b0; line-height: 1.5; }

  /* success */
  .inv-success {
    display: flex; flex-direction: column; align-items: center;
    text-align: center; gap: 14px; padding: 20px 0;
  }
  .inv-success-icon {
    width: 56px; height: 56px; border-radius: 50%;
    background: rgba(0,229,160,0.12); border: 1px solid rgba(0,229,160,0.25);
    display: flex; align-items: center; justify-content: center;
    color: #00e5a0;
  }
  .inv-success h2 {
    font-size: 20px; font-weight: 700; color: #e8e8f0;
    letter-spacing: -0.03em;
  }
  .inv-success p {
    font-size: 14px; color: #9494b0; line-height: 1.55; max-width: 280px;
  }
  .inv-success .inv-btn { margin-top: 4px; }

  /* loading */
  .inv-loading {
    display: flex; flex-direction: column; align-items: center;
    gap: 14px; padding: 20px 0; color: #9494b0; font-size: 14px;
  }
  .inv-spinner {
    display: inline-block; width: 26px; height: 26px;
    border: 2px solid #252530; border-top-color: #00e5a0; border-radius: 50%;
    animation: gt-spin 0.75s linear infinite;
  }

  /* header */
  .inv-head h1 {
    font-size: 22px; font-weight: 700; color: #e8e8f0;
    letter-spacing: -0.03em; margin-bottom: 8px;
  }
  .inv-head p  { font-size: 14px; color: #9494b0; line-height: 1.55; }
  .inv-head strong { color: #e8e8f0; font-weight: 500; }

  /* meta preview */
  .inv-meta {
    background: #18181f; border: 1px solid #252530; border-radius: 10px; overflow: hidden;
  }
  .inv-meta-row {
    display: flex; align-items: center; gap: 14px;
    padding: 11px 15px; border-bottom: 1px solid #252530;
  }
  .inv-meta-row:last-child { border-bottom: none; }
  .inv-meta-label { font-size: 11px; text-transform: uppercase; letter-spacing: 0.08em; color: #55556a; width: 44px; flex-shrink: 0; }
  .inv-meta-value { font-size: 14px; color: #e8e8f0; }

  /* form */
  .inv-form { display: flex; flex-direction: column; gap: 16px; }
  .inv-field { display: flex; flex-direction: column; gap: 7px; }
  .inv-field label { font-size: 12px; font-weight: 500; color: #9494b0; }
  .inv-field input {
    height: 42px; width: 100%;
    background: #18181f; border: 1px solid #252530; border-radius: 8px;
    padding: 0 13px; font-size: 14px; color: #e8e8f0; outline: none;
    transition: border-color 0.15s, box-shadow 0.15s; font-family: inherit;
  }
  .inv-field input::placeholder { color: #55556a; }
  .inv-field input:focus {
    border-color: #00e5a0; box-shadow: 0 0 0 3px rgba(0,229,160,0.1);
  }
  .inv-field input:disabled { opacity: 0.5; cursor: not-allowed; }

  /* strength bar */
  .inv-strength { display: flex; align-items: center; gap: 10px; }
  .inv-strength-bar {
    flex: 1; height: 3px; background: #252530; border-radius: 99px; overflow: hidden;
  }
  .inv-strength-fill { height: 100%; border-radius: 99px; transition: width 0.25s, background 0.25s; }
  .inv-strength-label { font-size: 11px; color: #55556a; white-space: nowrap; }

  /* error */
  .inv-error {
    display: flex; align-items: center; gap: 8px;
    background: rgba(248,113,113,0.08); border: 1px solid rgba(248,113,113,0.22);
    border-radius: 8px; padding: 9px 13px; font-size: 13px; color: #f87171;
  }

  /* submit */
  .inv-btn {
    height: 42px; width: 100%;
    background: #00e5a0; color: #09090f;
    font-size: 14px; font-weight: 600; border: none; border-radius: 8px;
    cursor: pointer; transition: background 0.15s;
    display: flex; align-items: center; justify-content: center;
    margin-top: 2px; font-family: inherit;
  }
  .inv-btn:hover:not(:disabled)  { background: #00ccad; }
  .inv-btn:disabled { opacity: 0.5; cursor: not-allowed; }
  .inv-spinner-sm {
    display: inline-block; width: 17px; height: 17px;
    border: 2px solid rgba(9,9,15,0.25); border-top-color: #09090f;
    border-radius: 50%; animation: gt-spin 0.7s linear infinite;
  }
  @keyframes gt-spin { to { transform: rotate(360deg); } }
`
