"""initial schema

Revision ID: 43e6e3f6ebb0
Revises: 
Create Date: 2026-05-12 00:18:45.107292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43e6e3f6ebb0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leads',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(length=500), nullable=False),
    sa.Column('company_or_brand', sa.String(length=500), nullable=True),
    sa.Column('job_title', sa.String(length=500), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('category', sa.Enum('CRYPTO_INFLUENCER', 'BLOCKCHAIN_PROJECT', 'BLOCKCHAIN_EXPERT', 'GOLF_INDUSTRY', 'TRAVEL_INDUSTRY', name='leadcategory'), nullable=False),
    sa.Column('status', sa.Enum('NEW', 'QUALIFIED', 'CONTACTED', 'RESPONDED', 'CONVERTED', 'DISQUALIFIED', name='leadstatus'), nullable=True),
    sa.Column('data_quality', sa.Enum('UNVERIFIED', 'VERIFIED', 'FLAGGED', 'REJECTED', name='dataquality'), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('email_primary', sa.String(length=255), nullable=True),
    sa.Column('email_secondary', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('linkedin_url', sa.String(length=500), nullable=True),
    sa.Column('linkedin_id', sa.String(length=100), nullable=True),
    sa.Column('twitter_handle', sa.String(length=100), nullable=True),
    sa.Column('instagram_handle', sa.String(length=100), nullable=True),
    sa.Column('telegram_handle', sa.String(length=100), nullable=True),
    sa.Column('youtube_channel', sa.String(length=500), nullable=True),
    sa.Column('other_social', sa.JSON(), nullable=True),
    sa.Column('ai_category_confidence', sa.Float(), nullable=True),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('ai_outreach_template', sa.Text(), nullable=True),
    sa.Column('ai_tags', sa.JSON(), nullable=True),
    sa.Column('ai_processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('relevance_score', sa.Float(), nullable=True),
    sa.Column('engagement_score', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('scraped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_contacted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_leads_category_country', 'leads', ['category', 'country'], unique=False)
    op.create_index('idx_leads_category_status', 'leads', ['category', 'status'], unique=False)
    op.create_index('idx_leads_relevance', 'leads', ['relevance_score'], unique=False)
    op.create_index(op.f('ix_leads_category'), 'leads', ['category'], unique=False)
    op.create_index(op.f('ix_leads_country'), 'leads', ['country'], unique=False)
    op.create_index(op.f('ix_leads_data_quality'), 'leads', ['data_quality'], unique=False)
    op.create_index(op.f('ix_leads_email_primary'), 'leads', ['email_primary'], unique=False)
    op.create_index(op.f('ix_leads_status'), 'leads', ['status'], unique=False)
    op.create_table('tags',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('field_changed', sa.String(length=100), nullable=True),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_lead_id'), 'audit_logs', ['lead_id'], unique=False)
    op.create_table('lead_blockchain',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=True),
    sa.Column('ecosystem', sa.Enum('POLYGON', 'SOLANA', 'ETHEREUM', 'OTHER', name='blockchainecosystem'), nullable=True),
    sa.Column('expert_type', sa.Enum('SECURITY_AUDITOR', 'LAWYER', 'DEVELOPER', 'CONSULTANT', 'OTHER', name='experttype'), nullable=True),
    sa.Column('project_name', sa.String(length=500), nullable=True),
    sa.Column('token_symbol', sa.String(length=20), nullable=True),
    sa.Column('mainnet_live', sa.Boolean(), nullable=True),
    sa.Column('tvl_usd', sa.Float(), nullable=True),
    sa.Column('github_url', sa.String(length=500), nullable=True),
    sa.Column('whitepaper_url', sa.String(length=500), nullable=True),
    sa.Column('funding_stage', sa.String(length=100), nullable=True),
    sa.Column('investors', sa.JSON(), nullable=True),
    sa.Column('specializations', sa.JSON(), nullable=True),
    sa.Column('certifications', sa.JSON(), nullable=True),
    sa.Column('audits_completed', sa.Integer(), nullable=True),
    sa.Column('github_handle', sa.String(length=100), nullable=True),
    sa.Column('years_experience', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lead_id')
    )
    op.create_index(op.f('ix_lead_blockchain_ecosystem'), 'lead_blockchain', ['ecosystem'], unique=False)
    op.create_table('lead_crypto',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=True),
    sa.Column('twitter_followers', sa.Integer(), nullable=True),
    sa.Column('youtube_subscribers', sa.Integer(), nullable=True),
    sa.Column('instagram_followers', sa.Integer(), nullable=True),
    sa.Column('telegram_members', sa.Integer(), nullable=True),
    sa.Column('total_reach', sa.Integer(), nullable=True),
    sa.Column('crypto_niches', sa.JSON(), nullable=True),
    sa.Column('chains_covered', sa.JSON(), nullable=True),
    sa.Column('past_promotions', sa.JSON(), nullable=True),
    sa.Column('collab_rate_usd', sa.Float(), nullable=True),
    sa.Column('accepts_token_payment', sa.Boolean(), nullable=True),
    sa.Column('has_kol_experience', sa.Boolean(), nullable=True),
    sa.Column('avg_engagement_rate', sa.Float(), nullable=True),
    sa.Column('verified_account', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lead_id')
    )
    op.create_table('lead_golf',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=True),
    sa.Column('golf_type', sa.String(length=100), nullable=True),
    sa.Column('handicap', sa.Float(), nullable=True),
    sa.Column('world_ranking', sa.Integer(), nullable=True),
    sa.Column('tour_affiliation', sa.String(length=255), nullable=True),
    sa.Column('sponsors', sa.JSON(), nullable=True),
    sa.Column('venue_name', sa.String(length=500), nullable=True),
    sa.Column('venue_address', sa.Text(), nullable=True),
    sa.Column('holes', sa.Integer(), nullable=True),
    sa.Column('membership_type', sa.String(length=100), nullable=True),
    sa.Column('green_fee_usd', sa.Float(), nullable=True),
    sa.Column('number_of_members', sa.Integer(), nullable=True),
    sa.Column('association_name', sa.String(length=500), nullable=True),
    sa.Column('association_country', sa.String(length=100), nullable=True),
    sa.Column('member_clubs', sa.Integer(), nullable=True),
    sa.Column('directory_verified', sa.Boolean(), nullable=True),
    sa.Column('directory_source', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lead_id')
    )
    op.create_table('lead_tags',
    sa.Column('lead_id', sa.UUID(), nullable=False),
    sa.Column('tag_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('lead_id', 'tag_id')
    )
    op.create_table('lead_travel',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=True),
    sa.Column('travel_type', sa.String(length=100), nullable=True),
    sa.Column('agency_name', sa.String(length=500), nullable=True),
    sa.Column('luxury_tier', sa.String(length=50), nullable=True),
    sa.Column('destinations_covered', sa.JSON(), nullable=True),
    sa.Column('annual_revenue_usd', sa.Float(), nullable=True),
    sa.Column('number_of_staff', sa.Integer(), nullable=True),
    sa.Column('instagram_followers', sa.Integer(), nullable=True),
    sa.Column('youtube_subscribers', sa.Integer(), nullable=True),
    sa.Column('blog_monthly_visitors', sa.Integer(), nullable=True),
    sa.Column('travel_niches', sa.JSON(), nullable=True),
    sa.Column('asean_focus', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lead_id')
    )
    op.create_table('outreach_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('channel', sa.Enum('EMAIL', 'LINKEDIN', 'TWITTER', 'TELEGRAM', 'WHATSAPP', 'OTHER', name='outreachchannel'), nullable=False),
    sa.Column('status', sa.Enum('PLANNED', 'SENT', 'OPENED', 'REPLIED', 'BOUNCED', name='outreachstatus'), nullable=True),
    sa.Column('subject', sa.String(length=500), nullable=True),
    sa.Column('message_body', sa.Text(), nullable=True),
    sa.Column('ai_generated', sa.Boolean(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('replied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reply_content', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outreach_logs_lead_id'), 'outreach_logs', ['lead_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_outreach_logs_lead_id'), table_name='outreach_logs')
    op.drop_table('outreach_logs')
    op.drop_table('lead_travel')
    op.drop_table('lead_tags')
    op.drop_table('lead_golf')
    op.drop_table('lead_crypto')
    op.drop_index(op.f('ix_lead_blockchain_ecosystem'), table_name='lead_blockchain')
    op.drop_table('lead_blockchain')
    op.drop_index(op.f('ix_audit_logs_lead_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('tags')
    op.drop_index(op.f('ix_leads_status'), table_name='leads')
    op.drop_index(op.f('ix_leads_email_primary'), table_name='leads')
    op.drop_index(op.f('ix_leads_data_quality'), table_name='leads')
    op.drop_index(op.f('ix_leads_country'), table_name='leads')
    op.drop_index(op.f('ix_leads_category'), table_name='leads')
    op.drop_index('idx_leads_relevance', table_name='leads')
    op.drop_index('idx_leads_category_status', table_name='leads')
    op.drop_index('idx_leads_category_country', table_name='leads')
    op.drop_table('leads')
    # ### end Alembic commands ###
